### PR TITLE
add starkOrderToMessageHash, and sort index

### PR DESCRIPTION
**Pull request by adrian-gierakowski**
NOTE: after adding new files to lib, index can be regenerated
with `js-make-index` script available on nix-shell started
from backend repo

### CODE REVIEW

**Review by arijoon — APPROVED** [review]

**Comment by adrian-gierakowski** [comment]
@arijoon I just pushed a commit bumping version in package.json, and it looks like we need the PR to be approved again

**Review by arijoon — APPROVED** [review]

**Comment by arijoon** [comment]
Actually I don't think my approval matters since I don't seem to have write access to this repo, @plutoegg or @konradstrachan will need to approve

**Comment by adrian-gierakowski** [comment]
looks like I can bypass the approval :)

**Comment by arijoon** [comment]
> looks like I can bypass the approval :)

Konrad just gave me write access so my approvals matter now :smile:

**Pull request merged**
